let json = `[{"id":1,"first_name":"Cornelia","last_name":"Hourigan","email":"chourigan0@sohu.com","gender":"Female","salary":1503},
{"id":2,"first_name":"Ambrosius","last_name":"MacCourt","email":"amaccourt1@cbsnews.com","gender":"Male","salary":3401},
{"id":3,"first_name":"Danya","last_name":"Just","email":"djust2@alexa.com","gender":"Female","salary":7872},
{"id":4,"first_name":"Jeremy","last_name":"Winch","email":"jwinch3@rediff.com","gender":"Male","salary":7711},
{"id":5,"first_name":"Wainwright","last_name":"Ambrogio","email":"wambrogio4@cbsnews.com","gender":"Male","salary":4806},
{"id":6,"first_name":"Malia","last_name":"Furmage","email":"mfurmage5@skype.com","gender":"Female","salary":2849},
{"id":7,"first_name":"Neall","last_name":"Bauckham","email":"nbauckham6@bigcartel.com","gender":"Male","salary":2761},
{"id":8,"first_name":"Hilary","last_name":"Sehorsch","email":"hsehorsch7@cafepress.com","gender":"Male","salary":3768},
{"id":9,"first_name":"Vonni","last_name":"Boxill","email":"vboxill8@hibu.com","gender":"Female","salary":2947},
{"id":10,"first_name":"Blythe","last_name":"Bisley","email":"bbisley9@unicef.org","gender":"Female","salary":8330},
{"id":11,"first_name":"Celle","last_name":"Moodie","email":"cmoodiea@ibm.com","gender":"Female","salary":5915},
{"id":12,"first_name":"Addie","last_name":"Mattusov","email":"amattusovb@techcrunch.com","gender":"Male","salary":8349},
{"id":13,"first_name":"Cindy","last_name":"Levet","email":"clevetc@ftc.gov","gender":"Female","salary":2954},
{"id":14,"first_name":"Bathsheba","last_name":"Quadling","email":"bquadlingd@scientificamerican.com","gender":"Female","salary":8237},
{"id":15,"first_name":"Karrah","last_name":"Ackhurst","email":"kackhurste@huffingtonpost.com","gender":"Female","salary":3704},
{"id":16,"first_name":"Annelise","last_name":"Blaik","email":"ablaikf@oakley.com","gender":"Female","salary":4945},
{"id":17,"first_name":"Fairleigh","last_name":"Heindle","email":"fheindleg@slideshare.net","gender":"Non-binary","salary":7784},
{"id":18,"first_name":"Rani","last_name":"Kaasmann","email":"rkaasmannh@eventbrite.com","gender":"Female","salary":6912},
{"id":19,"first_name":"Jourdain","last_name":"Shakesbye","email":"jshakesbyei@miitbeian.gov.cn","gender":"Male","salary":6806},
{"id":20,"first_name":"Palm","last_name":"Kilgrew","email":"pkilgrewj@joomla.org","gender":"Male","salary":1859}]`
let empAry = JSON.parse(json);
console.log(empAry);